from pathlib import Path

from scripts import gen_roster, gen_scope_matrix


ALOUS = {
    "AGENT-OPS01.alou.md": (
        "---\n"
        "agent_id: AGENT-OPS01\n"
        "role_title: \"Operations Steward\"\n"
        "version: \"1.1\"\n"
        "cluster_path:\n"
        "  chapter: \"Operations\"\n"
        "  squad: \"RunOps\"\n"
        "fs_write_scopes: [\"org/ops/**\", \"bus/alerts/**\"]\n"
        "mcp_allow: [\"file\", \"search\"]\n"
        "data_classification: internal\n"
        "---\n"
    ),
    "AGENT-ENG01.alou.md": (
        "---\n"
        "agent_id: AGENT-ENG01\n"
        "role_title: \"Engineering Synth\"\n"
        "version: \"1.1\"\n"
        "cluster_path:\n"
        "  chapter: \"Engineering\"\n"
        "  squad: \"Orchestrator\"\n"
        "  guilds: [\"Reliability\"]\n"
        "fs_write_scopes: [\"org/eng/**\"]\n"
        "mcp_allow: [\"file\", \"knowledge\"]\n"
        "data_classification: internal\n"
        "---\n"
    ),
}


def setup_repo(tmp_path: Path) -> Path:
    (tmp_path / "org/_registry").mkdir(parents=True)
    (tmp_path / "agents").mkdir()
    for name, text in ALOUS.items():
        (tmp_path / "org/_registry" / name).write_text(text, encoding="utf-8")
        agent_dir = tmp_path / "agents" / name.split(".")[0]
        agent_dir.mkdir(parents=True, exist_ok=True)
        (agent_dir / "prompt.md").write_text("prompt", encoding="utf-8")
    return tmp_path


def test_gen_roster(tmp_path: Path) -> None:
    base = setup_repo(tmp_path)
    output = gen_roster.write_roster(base)
    content = output.read_text(encoding="utf-8")
    assert "Generated by scripts/gen_roster.py" in content
    assert "`AGENT-OPS01`" in content
    assert "`org/ops/**`" in content


def test_gen_scope_matrix(tmp_path: Path) -> None:
    base = setup_repo(tmp_path)
    output = gen_scope_matrix.write_matrix(base)
    content = output.read_text(encoding="utf-8")
    assert "Generated by scripts/gen_scope_matrix.py" in content
    assert "`AGENT-ENG01`" in content
    assert "`org/eng/**`" in content
